In [101]:
#numpy ejercicios

In [102]:
import numpy as np

In [103]:
#Ejercicio 1
#Crea arrays de 1, 2 y 3 dimensiones. Las longitudes deben ser las siguientes, respectivamente: 6, 3 x 2 y 2 x 3 x 4

In [104]:
arr1=np.array(np.random.random(6))
print(arr1)
print(arr1.shape)
print(arr1.ndim)


[0.49635903 0.76988629 0.29325542 0.70150487 0.83022982 0.72394391]
(6,)
1


In [105]:
arr2=np.array(np.random.random([2,3]))
print(arr2)
print(arr2.shape)
print(arr2.ndim)

[[0.25863082 0.03858872 0.23481848]
 [0.19983787 0.70542121 0.59833726]]
(2, 3)
2


In [106]:
arr3=np.array(np.random.random([3,2,4]))
print(arr3)
print(arr3.shape)
print(arr3.ndim)

[[[0.25848748 0.14705802 0.93989503 0.23089992]
  [0.56207232 0.40700523 0.82922641 0.99899991]]

 [[0.05298059 0.08929522 0.09511085 0.44864486]
  [0.55546723 0.06215446 0.55731527 0.36245372]]

 [[0.96934539 0.09476062 0.31042705 0.56034279]
  [0.52668917 0.87108764 0.81808219 0.14685097]]]
(3, 2, 4)
3


In [107]:
arr11=np.array([1,2,3,3,5,6])
print(arr11)
print(arr11.shape)
print(arr11.ndim)

[1 2 3 3 5 6]
(6,)
1


In [108]:
# 1 matriz de 2 filas y 3 columnas
arr22=np.array([[1,2,3],[5,6,7]])
print(arr22)
print(arr22.shape)
print(arr22.ndim)

[[1 2 3]
 [5 6 7]]
(2, 3)
2


In [109]:
# 3x2x4 3 matrices de 2 filas y y columnas
arr22=np.array([[[1,2,3,4],[5,6,7,4]],[[1,2,3,5],[5,6,7,7]],[[1,2,3,5],[5,6,6,7]]])
print(arr22)
print(arr22.shape)
print(arr22.ndim)

[[[1 2 3 4]
  [5 6 7 4]]

 [[1 2 3 5]
  [5 6 7 7]]

 [[1 2 3 5]
  [5 6 6 7]]]
(3, 2, 4)
3


In [110]:
# Ejercicio 2.
#Crea una función que te haga un resumen estadístico básico de un array (cuartiles, mediana, media, varianza, etc) 
# si tiene una dimensión. Si tiene más de una, muestra un mensaje de alerta.

In [113]:
# con el return, se para; si pongo print sigue la función sea true o false
def f(arr1):
    if arr1.ndim>1:
        return ("El array debe ser de más de una dimensión")
    res={
        'media':np.mean(arr1),
        'desviación':np.std(arr1),
        'percentil50':np.percentile(arr1,50)}
    return res

In [114]:
print(f(arr1))

{'media': 0.6358632242821148, 'desviación': 0.18468401660037687, 'percentil50': 0.7127243899671392}


In [54]:
#Ejercicio 3.
#Crea un array de 3 dimensiones parecido al que te doy a continuación, y sin ejecutar las instrucciones siguientes,
# intenta razonar qué números devolverán (si funcionan, claro)

In [116]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15],[16, 17, 18]], [[19, 20, 21],[22, 23, 24]] ])
arr

#4x2x3


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [118]:
#últimas posiciones
print(arr[-1,-1,-1])

24


In [119]:
# posiciones 012
print(arr[0,1,:])

[4 5 6]


In [ ]:
# coge todas las matrices, coge todas las primeras filas y coge todas las columnas
print(arr[:,0,:])

[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]
 [19 20 21]]


In [124]:
print(arr[:,:,-1])
print(arr[:,:,2])

[[ 3  6]
 [ 9 12]
 [15 18]
 [21 24]]
[[ 3  6]
 [ 9 12]
 [15 18]
 [21 24]]


In [125]:
print(arr[2,1,0])

16


In [127]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [126]:
print(arr[::2,:,:])

[[[ 1  2  3]
  [ 4  5  6]]

 [[13 14 15]
  [16 17 18]]]


In [55]:
#Ejercicio 4.
#Crea un array de 3 x 3 que contenga valores aleatorios entre el 0 y el 100. 
# Tendrás que usar el submódulo random. Una vez tengas el código, 
# transfórmalo a una función que te permita crear arrays de tamaño N x N

In [56]:
#Ejercicio 5.
#Crea una función que dependa de un número. Si la función se ejecuta con el número 5, debe devolver el siguiente array:
# 1 1 1 1 1

#1 0 0 0 1

#1 0 0 0 1

# 1 0 0 0 1

# 1 1 1 1 1