In [44]:
#numpy ejercicios

In [45]:
import numpy as np

In [46]:
#Ejercicio 1
#Crea arrays de 1, 2 y 3 dimensiones. Las longitudes deben ser las siguientes, respectivamente: 6, 3 x 2 y 2 x 3 x 4

In [47]:
arr1=np.array(np.random.random(6))
print(arr1)
print(arr1.shape)
print(arr1.ndim)


[0.09583211 0.95519981 0.90497859 0.64518743 0.6382893  0.16021979]
(6,)
1


In [48]:
arr2=np.array(np.random.random([2,3]))
print(arr2)
print(arr2.shape)
print(arr2.ndim)

[[0.46544715 0.95925887 0.12126251]
 [0.81724904 0.81143752 0.06402209]]
(2, 3)
2


In [49]:
arr3=np.array(np.random.random([3,2,4]))
print(arr3)
print(arr3.shape)
print(arr3.ndim)

[[[0.70061636 0.50297216 0.84018152 0.2144497 ]
  [0.38340986 0.95814737 0.07281963 0.7286312 ]]

 [[0.77141202 0.34291843 0.58394787 0.87288268]
  [0.43655606 0.25610065 0.36156224 0.50440004]]

 [[0.50350502 0.90996551 0.76456571 0.12686076]
  [0.41597927 0.85863872 0.02419665 0.10157126]]]
(3, 2, 4)
3


In [50]:
arr11=np.array([1,2,3,3,5,6])
print(arr11)
print(arr11.shape)
print(arr11.ndim)

[1 2 3 3 5 6]
(6,)
1


In [51]:
# 1 matriz de 2 filas y 3 columnas
arr22=np.array([[1,2,3],[5,6,7]])
print(arr22)
print(arr22.shape)
print(arr22.ndim)

[[1 2 3]
 [5 6 7]]
(2, 3)
2


In [52]:
# 3x2x4 3 matrices de 2 filas y y columnas
arr22=np.array([[[1,2,3,4],[5,6,7,4]],[[1,2,3,5],[5,6,7,7]],[[1,2,3,5],[5,6,6,7]]])
print(arr22)
print(arr22.shape)
print(arr22.ndim)

[[[1 2 3 4]
  [5 6 7 4]]

 [[1 2 3 5]
  [5 6 7 7]]

 [[1 2 3 5]
  [5 6 6 7]]]
(3, 2, 4)
3


In [53]:
# Ejercicio 2.
#Crea una función que te haga un resumen estadístico básico de un array (cuartiles, mediana, media, varianza, etc) 
# si tiene una dimensión. Si tiene más de una, muestra un mensaje de alerta.

In [54]:
#Ejercicio 3.
#Crea un array de 3 dimensiones parecido al que te doy a continuación, y sin ejecutar las instrucciones siguientes,
# intenta razonar qué números devolverán (si funcionan, claro)

In [55]:
#Ejercicio 4.
#Crea un array de 3 x 3 que contenga valores aleatorios entre el 0 y el 100. 
# Tendrás que usar el submódulo random. Una vez tengas el código, 
# transfórmalo a una función que te permita crear arrays de tamaño N x N

In [56]:
#Ejercicio 5.
#Crea una función que dependa de un número. Si la función se ejecuta con el número 5, debe devolver el siguiente array:
# 1 1 1 1 1

#1 0 0 0 1

#1 0 0 0 1

# 1 0 0 0 1

# 1 1 1 1 1