In [24]:
#numpy ejercicios

In [25]:
import numpy as np

In [26]:
#Ejercicio 1
#Crea arrays de 1, 2 y 3 dimensiones. Las longitudes deben ser las siguientes, respectivamente: 6, 3 x 2 y 2 x 3 x 4

In [27]:
arr1=np.array(np.random.random(6))
print(arr1)
print(arr1.shape)
print(arr1.ndim)


[0.93469833 0.2541955  0.41349184 0.64824265 0.29251753 0.80123848]
(6,)
1


In [28]:
arr2=np.array(np.random.random([2,3]))
print(arr2)
print(arr2.shape)
print(arr2.ndim)

[[0.72047123 0.17383896 0.29061318]
 [0.34496983 0.31833497 0.45919008]]
(2, 3)
2


In [29]:
arr3=np.array(np.random.random([3,2,4]))
print(arr3)
print(arr3.shape)
print(arr3.ndim)

[[[0.45024908 0.7947633  0.94725932 0.43049917]
  [0.57142332 0.59116934 0.53860052 0.92569177]]

 [[0.29850004 0.90835659 0.97271798 0.97501944]
  [0.12179895 0.79751264 0.41345102 0.29358005]]

 [[0.27885566 0.03679043 0.88485598 0.33435016]
  [0.62171236 0.69279292 0.71844745 0.3265067 ]]]
(3, 2, 4)
3


In [30]:
arr11=np.array([1,2,3,3,5,6])
print(arr11)
print(arr11.shape)
print(arr11.ndim)

[1 2 3 3 5 6]
(6,)
1


In [31]:
# 1 matriz de 2 filas y 3 columnas
arr22=np.array([[1,2,3],[5,6,7]])
print(arr22)
print(arr22.shape)
print(arr22.ndim)

[[1 2 3]
 [5 6 7]]
(2, 3)
2


In [32]:
# 3x2x4 3 matrices de 2 filas y y columnas
arr22=np.array([[[1,2,3,4],[5,6,7,4]],[[1,2,3,5],[5,6,7,7]],[[1,2,3,5],[5,6,6,7]]])
print(arr22)
print(arr22.shape)
print(arr22.ndim)

[[[1 2 3 4]
  [5 6 7 4]]

 [[1 2 3 5]
  [5 6 7 7]]

 [[1 2 3 5]
  [5 6 6 7]]]
(3, 2, 4)
3


In [33]:
# Ejercicio 2.
#Crea una función que te haga un resumen estadístico básico de un array (cuartiles, mediana, media, varianza, etc) 
# si tiene una dimensión. Si tiene más de una, muestra un mensaje de alerta.

In [34]:
# con el return, se para; si pongo print sigue la función sea true o false
def f(arr1):
    if arr1.ndim>1:
        return ("El array debe ser de más de una dimensión")
    res={
        'media':np.mean(arr1),
        'desviación':np.std(arr1),
        'percentil50':np.percentile(arr1,50)}
    return res

In [35]:
print(f(arr1))

{'media': 0.557397389030949, 'desviación': 0.2558869773638198, 'percentil50': 0.5308672426713765}


In [36]:
#Ejercicio 3.
#Crea un array de 3 dimensiones parecido al que te doy a continuación, y sin ejecutar las instrucciones siguientes,
# intenta razonar qué números devolverán (si funcionan, claro)

In [37]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15],[16, 17, 18]], [[19, 20, 21],[22, 23, 24]] ])
arr

#4x2x3


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [38]:
#últimas posiciones
print(arr[-1,-1,-1])

24


In [39]:
# posiciones 012
print(arr[0,1,:])

[4 5 6]


In [40]:
# coge todas las matrices, coge todas las primeras filas y coge todas las columnas
print(arr[:,0,:])

[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]
 [19 20 21]]


In [41]:
print(arr[:,:,-1])
print(arr[:,:,2])

[[ 3  6]
 [ 9 12]
 [15 18]
 [21 24]]
[[ 3  6]
 [ 9 12]
 [15 18]
 [21 24]]


In [42]:
print(arr[2,1,0])

16


In [43]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [44]:
print(arr[::2,:,:])

[[[ 1  2  3]
  [ 4  5  6]]

 [[13 14 15]
  [16 17 18]]]


In [45]:
#Ejercicio 4.
#Crea un array de 3 x 3 que contenga valores aleatorios entre el 0 y el 100. Tendrás que usar el submódulo random.
# Una vez tengas el código, transfórmalo a una función que te permita crear arrays de tamaño N x N

In [54]:
arr3x3=np.random.random([3,3])*100
arr3x3

array([[86.40442316,  5.86326311,  3.06137564],
       [ 0.35101603, 99.22556913, 93.40096853],
       [42.02858345, 96.73819489, 43.79704066]])

In [70]:
def ran_arr(n):
    return np.random.random([n,n])*100

In [71]:
a=3
ran_arr(a)

array([[85.21230179, 18.05911782, 83.81685629],
       [ 7.15240643, 32.89032468, 22.09812165],
       [79.82553143, 37.25945834, 11.30928095]])

In [78]:
def ran_arr(n):
    if n<=0:
        return "No válido"
    return np.random.random([n,n])*100

In [79]:
a=0
ran_arr(a)

'No válido'

In [46]:
#Ejercicio 5. Crea una función que dependa de un número. 
# Si la función se ejecuta con el número 5, debe devolver el siguiente array:
# 1 1 1 1 1

#1 0 0 0 1

#1 0 0 0 1

# 1 0 0 0 1

# 1 1 1 1 1

In [88]:
arr1=np.ones([5,5])
arr0=np.zeros([3,3])
print(arr1)
print(arr0)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [99]:
# hay que posicionarse en la posición (1,1) hasta (3,3); 1:4 son ñas filas de la 1 a la 3, y de la columna 1 a 3
arr0=arr1[1:4,1:4]
print(arr0)
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [102]:
def gen_01(n):
    arr1=np.ones([n,n])
    arr1[1:n-1,1:n-1]=0
    return arr1

In [106]:
a=9
gen_01(a)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
def gen_cuadrado_1_0(n):
    ones = np.ones([n,n])
    ones[1:n-1,1:n-1] = 0

    return ones

print(gen_cuadrado_1_0(20))

In [ ]:
#Ejercicio 6.Crea una función que te detecte las dimensiones de un array, 
# y te diga cuántos datos faltantes contiene. Crea unos datos de ejemplo para comprobarlo.

In [136]:
arr_na = np.ones([3,3])
arr_na[1,1] = np.nan
arr_na[2,0] = np.nan
arr_na

array([[ 1.,  1.,  1.],
       [ 1., nan,  1.],
       [nan,  1.,  1.]])

In [137]:
np.isnan(arr_na)

array([[False, False, False],
       [False,  True, False],
       [ True, False, False]])

In [138]:
np.sum(np.isnan(arr_na))

2

In [139]:
sum(np.isnan(arr_na))

array([1, 1, 0])

In [140]:
#flatten para aplanar matriz
arr_na.flatten()

array([ 1.,  1.,  1.,  1., nan,  1., nan,  1.,  1.])

In [143]:
np.isnan((arr_na.flatten()))

array([False, False, False, False,  True, False,  True, False, False])

In [144]:
sum(np.isnan((arr_na.flatten())))

2

In [148]:
def f(arr):
    arr_na2={'dimensión':arr.ndim,'nam':sum(np.isnan((arr_na.flatten())))}
    return arr_na2
    

In [152]:
a=arr_na
f(a)

{'dimensión': 2, 'nam': 2}

In [ ]:
#Ejercicio 7. Crea una función que te calcule los márgenes de una tabla, es decir, 
# la suma por columnas, la suma por filas y el total. Idealmente, añadelo a la tabla original

In [155]:
arr7 = np.array([[3,2,1,2],[6,7,9,5]])
arr7

array([[3, 2, 1, 2],
       [6, 7, 9, 5]])

In [157]:
np.sum(arr7)

35

In [159]:
sum(arr7.flatten())

35

In [169]:
arr7
# [3,2,1,2,8]
# [6,7,9,5,27]
# [9,9,10,7,35]

array([[3, 2, 1, 2],
       [6, 7, 9, 5]])

In [203]:
sum1=(np.sum(arr7,axis=1))
sum2=(np.sum(arr7,axis=0))
sumt=np.array([np.sum(arr7)])
print(sum1)
print(sum2)
print(sumt)

[ 8 27]
[ 9  9 10  7]
[35]


In [202]:
sum11=sum1.reshape(2,1)
print(sum11)
sumtt=np.vstack((sum11,sumt))
print(sumtt)

[[ 8]
 [27]]
[[ 8]
 [27]
 [35]]


In [204]:
arr7

array([[3, 2, 1, 2],
       [6, 7, 9, 5]])

In [214]:
arrh=np.vstack((arr7,sum2)) #vstack añade una fila
print(arrh)
arrv=np.hstack((arrh,sumtt)) #hstack añade una columna
print(arrv)

[[ 3  2  1  2]
 [ 6  7  9  5]
 [ 9  9 10  7]]
[[ 3  2  1  2  8]
 [ 6  7  9  5 27]
 [ 9  9 10  7 35]]


In [215]:
def matriz(arr): #ponemos todos los conceptos
    sum1=(np.sum(arr,axis=1))
    sum2=(np.sum(arr,axis=0))
    sumt=np.array([np.sum(arr)])
    sum11=sum1.reshape(2,1)
    sumtt=np.vstack((sum11,sumt))
    arrh=np.vstack((arr,sum2)) 
    arrv=np.hstack((arrh,sumtt))
    return arrv
    

In [216]:
matriz(arr7)

array([[ 3,  2,  1,  2,  8],
       [ 6,  7,  9,  5, 27],
       [ 9,  9, 10,  7, 35]])

In [217]:
#Ejercicio 8.
#Crea una función que dados dos arrays X e Y,
# te calcule el coeficiente de correlación entre ellos usando la siguiente fórmula

In [218]:
x = np.array([2,3,4,6,7,8,9,7])
y = np.array([5,6,8,5,10,8,9,5])

# corr: -1 , 1 (0,75)

In [219]:
media_x = np.mean(x)
media_y = np.mean(y)

In [221]:
numerador = np.sum((x-media_x)*(y-media_y))
numerador

18.0

In [222]:
denominador = np.sqrt(np.sum((x-media_x)**2)) * np.sqrt(np.sum((y-media_y)**2))
denominador

34.8998567332303

In [223]:
corr = numerador/denominador
corr

0.5157614295551275

In [228]:
def coef_corr(x, y):
    if (x.ndim != 1 or y.ndim != 1) and (len(x) != len(y)):
        return 'x e y deben ser de 1 dim y misma longitud'

    media_x = np.mean(x)
    media_y = np.mean(y)
    numerador = np.sum((x-media_x)*(y-media_y))
    denominador = np.sqrt(np.sum((x-media_x)**2)) * \
        np.sqrt(np.sum((y-media_y)**2))

    if denominador == 0:
        return 'Error, denominador 0'

    corr = numerador/denominador

    return corr

In [225]:
coef_corr(x,y)

0.5157614295551275