In [586]:
#Numpy es permite procesar gran volumen de datos de forma matricial de forma eficiente

In [1]:
#! pip install numpy
import numpy as np

In [2]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
a1.shape

(3,)

In [589]:
print(a1)

[1 2 3]


In [4]:
a2=np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a2.shape

(2, 3)

In [591]:
a2[0]

array([1, 2, 3])

In [592]:
a2[1]

array([4, 5, 6])

In [593]:
a2[1,2]

6

In [594]:
a3=np.array([[[1,2,3],[4,5,6]],[[9,10,11],[12,13,14]],[[15,16,17],[18,19,20]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20]]])

In [595]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [596]:
a3[0,0]

array([1, 2, 3])

In [597]:
a3[0,0,1]

2

In [598]:
#para ver el 19
a3[2,1,1]

19

In [599]:
av1=np.empty(4)
av1

array([67.,  2.,  7.,  4.])

In [600]:
#genera un array de 2 dimensiones
av2=np.empty([2,3])
av2

array([[4.67325179e-310, 0.00000000e+000, 2.12199579e-312],
       [2.56761491e-312, 2.14321575e-312, 2.22809558e-312]])

In [601]:
#genera un array de 3 dimensiones; los números son valores de reserva
av3=np.empty([2,3,6])
av3

array([[[4.67325102e-310, 0.00000000e+000, 6.95056923e-310,
         6.95056923e-310, 6.95056920e-310, 6.95054417e-310],
        [6.95056920e-310, 6.95056920e-310, 6.95056920e-310,
         6.95056924e-310, 6.95056856e-310, 6.95056709e-310],
        [6.95056924e-310, 6.95056901e-310, 6.95056900e-310,
         6.95056855e-310, 6.95054436e-310, 6.95056900e-310]],

       [[6.95056896e-310, 6.95056895e-310, 6.95056901e-310,
         6.95056916e-310, 6.95056902e-310, 6.95056923e-310],
        [6.95056922e-310, 6.95056900e-310, 6.95056911e-310,
         6.95056920e-310, 6.95056923e-310, 6.95056925e-310],
        [6.95054431e-310, 6.95054427e-310, 6.95056923e-310,
         6.95056901e-310, 6.95056923e-310, 6.95056901e-310]]])

In [602]:
az=np.zeros([3,5])
az

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [603]:
auno=np.ones([3,5])
auno

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [604]:
af=np.full([3,5],9)
af

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [605]:
ai=np.identity(5)
ai

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [606]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes 

In [607]:
#viene bien para rellenar datos
ar=np.arange(1,10,2)
ar

array([1, 3, 5, 7, 9])

In [608]:
# saca 20 valores
al=np.linspace(1,100,20)
al

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [609]:
aran=np.random.random([2,3])
aran

array([[0.74503945, 0.2244087 , 0.7375188 ],
       [0.57026253, 0.91849342, 0.52699119]])

In [610]:
aran.ndim

2

In [611]:
aran.shape

(2, 3)

In [612]:
aran.size

6

In [613]:
aran.dtype

dtype('float64')

In [614]:
#numpy no permite que los datos sean de distinto tipo; los dataframes si!
at=np.array(['hola','marta'])
at

array(['hola', 'marta'], dtype='<U5')

In [615]:
at.dtype

dtype('<U5')

In [616]:
al

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [617]:
al.dtype

dtype('float64')

In [618]:
al.astype('i')

array([  1,   6,  11,  16,  21,  27,  32,  37,  42,  47,  53,  58,  63,
        68,  73,  79,  84,  89,  94, 100], dtype=int32)

In [619]:
aran

array([[0.74503945, 0.2244087 , 0.7375188 ],
       [0.57026253, 0.91849342, 0.52699119]])

In [620]:
np.sort(aran)

array([[0.2244087 , 0.7375188 , 0.74503945],
       [0.52699119, 0.57026253, 0.91849342]])

In [621]:
np.sort(aran,1)

array([[0.2244087 , 0.7375188 , 0.74503945],
       [0.52699119, 0.57026253, 0.91849342]])

In [622]:
np.sort(aran,0)

array([[0.57026253, 0.2244087 , 0.52699119],
       [0.74503945, 0.91849342, 0.7375188 ]])

In [623]:
arr = np.array([2, 4, 5, 0, 6, 1, 5, 4, 1, -3])

In [624]:
np.max(arr)

6

In [625]:
np.unique(arr)

array([-3,  0,  1,  2,  4,  5,  6])

In [626]:
np.exp(arr)

array([7.38905610e+00, 5.45981500e+01, 1.48413159e+02, 1.00000000e+00,
       4.03428793e+02, 2.71828183e+00, 1.48413159e+02, 5.45981500e+01,
       2.71828183e+00, 4.97870684e-02])

In [627]:
np.prod(arr)

0

In [628]:
np.NaN

nan

In [629]:
arr

array([ 2,  4,  5,  0,  6,  1,  5,  4,  1, -3])

In [630]:
for x in arr:
    print(x)

2
4
5
0
6
1
5
4
1
-3


In [631]:
for x in range(len(arr)):
    print (x,arr[x])

0 2
1 4
2 5
3 0
4 6
5 1
6 5
7 4
8 1
9 -3


In [632]:
aran

array([[0.74503945, 0.2244087 , 0.7375188 ],
       [0.57026253, 0.91849342, 0.52699119]])

In [633]:
for x in aran:
    print(x)

[0.74503945 0.2244087  0.7375188 ]
[0.57026253 0.91849342 0.52699119]


In [634]:
#para aplanar 2 dimensiones
for x in aran:
    for y in x:
        print(y)

0.7450394461740784
0.2244086956219421
0.7375187954160031
0.5702625263497862
0.9184934159140141
0.5269911886710958


In [635]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20]]])

In [636]:
for x in a3:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 9 10 11]
 [12 13 14]]
[[15 16 17]
 [18 19 20]]


In [637]:
#anidamiento que no es muy eficiente
for x in a3:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
9
10
11
12
13
14
15
16
17
18
19
20


In [638]:
for x in np.nditer(a3):
    print(x)

1
2
3
4
5
6
9
10
11
12
13
14
15
16
17
18
19
20


In [639]:
for pos,x in np.ndenumerate(a3):
    print (pos,x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 9
(1, 0, 1) 10
(1, 0, 2) 11
(1, 1, 0) 12
(1, 1, 1) 13
(1, 1, 2) 14
(2, 0, 0) 15
(2, 0, 1) 16
(2, 0, 2) 17
(2, 1, 0) 18
(2, 1, 1) 19
(2, 1, 2) 20


In [640]:
np.where(a3==10)

(array([1]), array([0]), array([1]))

In [641]:
np.where(a3>5)

(array([0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]),
 array([1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1]),
 array([2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [642]:
a1

array([1, 2, 3])

In [643]:
a1[a1>1]

array([2, 3])

In [644]:
#Desde el 0 hasta el 1, pero sin incluir el 1
a1[:1]

array([1])

In [645]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [646]:
a2[a2>1]

array([2, 3, 4, 5, 6])

In [647]:
# coge las filas 0 y 1 (no incluye el 2) y selecciona los elementos "0", es decir, el 1 y el 4
a2[:2,:1]

array([[1],
       [4]])

In [648]:
# coge las filas 0 y 1 (no cuenta 2) y coge los elementos desde la posición 1
a2[:2,1:]

array([[2, 3],
       [5, 6]])

In [649]:
a2[(a2>1) & (a2%2==0)]

array([2, 4, 6])

In [650]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

In [651]:
#necesita una tupla
arr3=np.concatenate((arr1,arr2))
arr3


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [652]:
# cocatena por columnas axis=0
arr3=np.concatenate((arr1,arr2), axis=0)
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [653]:
# cocatena por filas axis=1
arr3=np.concatenate((arr1,arr2), axis=1)
arr3

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [654]:
arr4=np.stack((arr1,arr2),axis=0)
arr4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [655]:
arr4=np.stack((arr1,arr2),axis=1)
arr4

array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]]])

In [656]:
arr3

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [657]:
# 3 dimensiones
arr5=np.array_split(arr3,3, axis=1)
arr5

[array([[1, 2],
        [4, 5]]),
 array([[ 3,  7],
        [ 6, 10]]),
 array([[ 8,  9],
        [11, 12]])]

In [658]:
# 2 dimensiones
arr5=np.array_split(arr3,3, axis=0)
arr5

[array([[1, 2, 3, 7, 8, 9]]),
 array([[ 4,  5,  6, 10, 11, 12]]),
 array([], shape=(0, 6), dtype=int64)]

In [659]:
# 3 dimensiones
arr5=np.array_split(arr3,3, axis=1)
arr5

for x in arr5:
    print(x)

[[1 2]
 [4 5]]
[[ 3  7]
 [ 6 10]]
[[ 8  9]
 [11 12]]


In [660]:
arr6= np.array([1, 2, np.nan, 7, 4, 0])
print(arr6)


[ 1.  2. nan  7.  4.  0.]


In [661]:
#no suma cuando encuentra ek vacío/error
sum(arr6)

nan

In [662]:
# cuando usas un bucle for para iterar sobre un array, x es una copia del valor del elemento, 
# no una referencia al elemento en sí. Por lo tanto, cualquier cambio en x no se reflejará en el array original.
for x in arr6:
    if np.isnan(x):
        x=0
print(arr6)

[ 1.  2. nan  7.  4.  0.]


In [663]:
#Para modificar el array original, necesitas acceder a los elementos del array a través de sus índices
for i in range(len(arr6)):  # Este bucle for itera sobre cada índice del array.En cada iteración, i toma el valor desde 0 hasta 5.
    if np.isnan(arr6[i]):
        arr6[i]=0
print(arr6)        

[1. 2. 0. 7. 4. 0.]


In [664]:
# con este bucle anidado sí que cambia el valor
lista=[x/2 for x in arr6]
lista

[0.5, 1.0, 0.0, 3.5, 2.0, 0.0]

In [665]:
lista=[x for x in arr6 if not np.isnan(x)]
np.array(lista)

array([1., 2., 0., 7., 4., 0.])

In [666]:
np.isnan(arr6)

array([False, False, False, False, False, False])

In [667]:
arr6[np.logical_not(np.isnan(arr6))]

array([1., 2., 0., 7., 4., 0.])

In [668]:
arr6[np.isfinite(arr6)]

array([1., 2., 0., 7., 4., 0.])

In [669]:
arr6

array([1., 2., 0., 7., 4., 0.])

In [670]:
copia=np.copy(arr6)
vista=arr6.view()
print('original:',arr6)
print('copia:',copia)
print('vista:',vista)

arr6[0]=67

copia=np.copy(arr6)
vista=arr6.view()
print('original:',arr6)
print('copia:',copia)
print('vista:',vista)


original: [1. 2. 0. 7. 4. 0.]
copia: [1. 2. 0. 7. 4. 0.]
vista: [1. 2. 0. 7. 4. 0.]
original: [67.  2.  0.  7.  4.  0.]
copia: [67.  2.  0.  7.  4.  0.]
vista: [67.  2.  0.  7.  4.  0.]


In [671]:
arr6.dtype

dtype('float64')

In [672]:
vista=arr6.view(dtype="float32")
print (vista)

[0.        3.2617188 0.        2.        0.        0.        0.
 2.4375    0.        2.25      0.        0.       ]


In [ ]:
# Clase 2 Numpy +Pandas

In [675]:
arr7=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr8=arr7.reshape([4,3])
arr8

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [678]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1, 1], [2, 2, 2]])
print(a)
print(b)
print(a*b)
print(a+b)
print(a*2)

[[1 2 3]
 [4 5 6]]
[[1 1 1]
 [2 2 2]]
[[ 1  2  3]
 [ 8 10 12]]
[[2 3 4]
 [6 7 8]]
[[ 2  4  6]
 [ 8 10 12]]


In [680]:
a = np.array([[1, 2], [4, 5]])
b = np.array([[1, 1], [2, 2]])
print(a*b)
print(a @ b)

[[ 1  2]
 [ 8 10]]
[[ 5  5]
 [14 14]]


In [681]:
print(np.linalg.norm(a))

6.782329983125268


In [682]:
a

array([[1, 2],
       [4, 5]])

In [683]:
a.T

array([[1, 4],
       [2, 5]])

In [684]:
np.linalg.det(a)

-2.9999999999999996

In [687]:
#  1x + 2y = 1
#  3x + 5y = 2

a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
print(a)
print(b)

np.linalg.solve(a, b)

[[1 2]
 [3 5]]
[1 2]


array([-1.,  1.])